# Generated by Django 4.2.4 on 2023-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('entry_price', models.IntegerField()),
                ('exit_price', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('observations', models.TextField(verbose_name='')),
                ('setup_image', models.ImageField(upload_to='')),
                ('reasons_for_entry', models.TextField(verbose_name='')),
            ],
        ),
    ]
