# Generated by Django 4.2.4 on 2023-08-27 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trade',
            name='custom_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='position',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], default=('Long', 'Long'), max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='setup_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
