# Generated by Django 4.2.4 on 2023-08-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myJournal', '0002_trade_created_at_trade_custom_user_trade_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
